# Generated by Django 5.1.6 on 2025-03-28 11:59

import django.db.models.deletion
import my_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinquiry',
            name='business_number',
            field=models.CharField(blank=True, default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='city',
            field=models.CharField(default='Unknown City', max_length=50),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='gstnumber',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='pannumber',
            field=models.CharField(default='AAAAA0000A', max_length=10, unique=True, validators=[my_app.models.validate_pan_number]),
        ),
        migrations.AddField(
            model_name='businessinquiry',
            name='pin',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='business_name',
            field=models.CharField(default='No Business Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
