# Generated by Django 5.1.6 on 2025-04-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_businessinquiry_business_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinquiry',
            name='business_number',
            field=models.CharField(blank=True, default='0000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='businessinquiry',
            name='gstnumber',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
